spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/calendar
    username: calendar
    password: calendar123
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/calendar
          wk-set-uri: http://localhost:8080/auth/realms/calendar/openid-connect/certs
keycloak:
  realm: calendar
  resource: calendar-app
  auth-server-url: http://localhost:8080/auth
server:
  port: 8081
  #servlet:
    #context-path: /calendar/all
